#!/usr/bin/env python3
"""Writes watchapp/source/Secrets.mc from the repo's .env (RELAY_TOKEN, PUBLIC_URL).

Secrets.mc is git-ignored. Re-run after changing .env, then rebuild the app.
The token ends up inside the compiled .prg on your watch: use this only for your own watch.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load_env() -> dict:
    env = {}
    path = ROOT / ".env"
    if not path.is_file():
        sys.exit("no .env in repo root (copy .env.example)")
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip().strip("'\"")
    return env


def main() -> None:
    env = load_env()
    url = env.get("PUBLIC_URL", "").rstrip("/")
    token = env.get("RELAY_TOKEN", "")
    if not url.startswith("https://"):
        sys.exit("PUBLIC_URL must be set in .env and start with https:// (the watch requires HTTPS)")
    if len(token) < 16 or token == "change-me":
        sys.exit("RELAY_TOKEN missing or too short in .env")
    for name, value in (("PUBLIC_URL", url), ("RELAY_TOKEN", token)):
        if not re.fullmatch(r"[A-Za-z0-9_:/.\-]+", value):
            sys.exit(f"{name} contains characters this generator does not escape")
    out = ROOT / "watchapp" / "source" / "Secrets.mc"
    out.write_text(
        "// GENERATED by watchapp/gen_config.py from .env - do not edit, do not commit.\n"
        "module Secrets {\n"
        f'    const RELAY_URL = "{url}";\n'
        f'    const RELAY_TOKEN = "{token}";\n'
        "}\n"
    )
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
